services:
#  redis:
#    restart: always
#    image: redis/redis-stack:6.2.6-v17
#    container_name: redis
#    ports:
#      - "6380:6379"
#      - "8001:8001"
#    volumes:
#      - ./docker-volumes/redis/data:/data
#      - ./docker-volumes/redis/configs/local-redis-stack.conf:/redis-stack.conf
#  test_line_provider_db:
#    restart: always
#    image: postgres
#    container_name: test_line-provider-db
#    environment:
#      POSTGRES_DB: test_line_provider
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: password
#    ports:
#      - "5434:5432"
#
#  line_provider_db:
#    restart: always
#    image: postgres
#    container_name: line-provider-db
#    environment:
#      POSTGRES_DB: line_provider
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: password
#    ports:
#      - "5433:5432"

  test_score_maker_db:
    restart: always
    image: postgres
    container_name: test_score_maker_db
    environment:
      POSTGRES_DB: test_score_maker_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"

  score_maker_db:
    restart: always
    image: postgres
    container_name: score_maker_db
    environment:
      POSTGRES_DB: score_maker_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
