services:
  redis:
    restart: always
    image: redis/redis-stack:6.2.6-v17
    container_name: redis
    ports:
      - "6380:6379"
      - "8001:8001"
    volumes:
      - ./docker-volumes/redis/data:/data
      - ./docker-volumes/redis/configs/local-redis-stack.conf:/redis-stack.conf

  db:
    restart: always
    image: postgres
    container_name: line-provider-db
    environment:
      POSTGRES_DB: line_provider
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

  test_db:
    restart: always
    image: postgres
    container_name: test_line-provider-db
    environment:
      POSTGRES_DB: test_line_provider
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"

