services:
  redis:
    restart: always
    image: redis/redis-stack:6.2.6-v17
    container_name: redis
    ports:
      - "6380:6379"
      - "8001:8001"
    volumes:
      - ./docker-volumes/redis/data:/data
      - ./docker-volumes/redis/configs/local-redis-stack.conf:/redis-stack.conf