services:
  redis:
    restart: always
    image: redis/redis-stack:6.2.6-v17
    container_name: redis
    ports:
      - "6380:6379"
      - "8001:8001"
    volumes:
      - ./docker-volumes/redis/data:/data
      - ./docker-volumes/redis/configs/local-redis-stack.conf:/redis-stack.conf

  line_provider_db:
    restart: always
    image: postgres
    container_name: line_provider_db
    environment:
      POSTGRES_DB: line_provider
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./docker-volumes/db:/var/lib/postgresql/data

  app:
    container_name: line_provider_service
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
      - redis
    restart: on-failure:5  # Restart the container up to 5 times on failure
    env_file:
      - .env
    command: bash -c "./scripts/wait_for_db.sh && alembic upgrade head || echo 'Alembic upgrade failed' && python ./src/entrypoints/app.py"
    ports:
      - "8555:8005"

