services:
  redis:
    restart: always
    image: redis/redis-stack:6.2.6-v17
    container_name: redis
    ports:
      - "6380:6379"
      - "8001:8001"
    volumes:
      - ./docker-volumes/redis/data:/data
      - ./docker-volumes/redis/configs/local-redis-stack.conf:/redis-stack.conf

  db:
    restart: always
    image: postgres
    container_name: line-provider-db
    environment:
      POSTGRES_DB: line_provider
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

  app:
    container_name: line_provider_service
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
      - redis
    restart: always
    environment:
      LINE_PROVIDER_CONFIG__REDIS__URL: redis://redis:6379
      LINE_PROVIDER_CONFIG__DB__URL: postgresql+asyncpg://user:password@db:5432/line_provider
    command: bash -c "./scripts/wait_for_db.sh && alembic upgrade head || echo 'Alembic upgrade failed' && uvicorn src.entrypoints.app:app --host 0.0.0.0 --port 8005"
    ports:
      - "8555:8005"

  test_db:
    restart: always
    image: postgres
    container_name: test_line-provider-db
    environment:
      POSTGRES_DB: test_line_provider
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"

